### ISSUE TITLE
Is it possible to add "count"?

### ISSUE THREAD

**Issue by theandychung** [nooperpudd/weibopy#1]
I want to get the most recent one or two posts on my timeline, is it possible to get just a few number of posts I want instead of all the posts on my timeline?

**Comment by nooperpudd** [comment]
@theandychung  http://open.weibo.com/wiki/2/statuses/home_timeline, read weibo api document carefully.

**Comment by theandychung** [comment]
Sorry, I still don't get it. Could you tell me where I should be reading more carefully?

**Comment by nooperpudd** [comment]
@theandychung 
http://open.weibo.com/wiki/2/statuses/home_timeline
